# Generated by Django 3.0.6 on 2020-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_demand_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
