# Generated by Django 3.0.6 on 2020-05-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_plant_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_heavy_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insulated_glass_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laminated_complex_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laminated_simple_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialty_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Plant')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Layout')),
            ],
        ),
    ]
